// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

public interface HotelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Hotel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ime = 1;</code>
   * @return The ime.
   */
  java.lang.String getIme();
  /**
   * <code>string ime = 1;</code>
   * @return The bytes for ime.
   */
  com.google.protobuf.ByteString
      getImeBytes();

  /**
   * <code>int32 zvezdice = 2;</code>
   * @return The zvezdice.
   */
  int getZvezdice();

  /**
   * <code>int32 udaljenosti_od_centra = 3;</code>
   * @return The udaljenostiOdCentra.
   */
  int getUdaljenostiOdCentra();

  /**
   * <code>int32 broj_slobodnih_mesta = 4;</code>
   * @return The brojSlobodnihMesta.
   */
  int getBrojSlobodnihMesta();

  /**
   * <code>int32 trenutna_cena = 5;</code>
   * @return The trenutnaCena.
   */
  int getTrenutnaCena();

  /**
   * <code>string grad = 6;</code>
   * @return The grad.
   */
  java.lang.String getGrad();
  /**
   * <code>string grad = 6;</code>
   * @return The bytes for grad.
   */
  com.google.protobuf.ByteString
      getGradBytes();

  /**
   * <code>int32 id = 7;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 broj_dana_boravka = 10;</code>
   * @return The brojDanaBoravka.
   */
  int getBrojDanaBoravka();

  /**
   * <code>int64 pocetakBoravka = 11;</code>
   * @return The pocetakBoravka.
   */
  long getPocetakBoravka();

  /**
   * <code>int32 interniRacun = 12;</code>
   * @return The interniRacun.
   */
  int getInterniRacun();

  /**
   * <code>int32 provizniRacun = 13;</code>
   * @return The provizniRacun.
   */
  int getProvizniRacun();

  /**
   * <code>int64 datumPlacanja = 14;</code>
   * @return The datumPlacanja.
   */
  long getDatumPlacanja();
}
