// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

/**
 * Protobuf type {@code Hotel}
 */
public final class Hotel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Hotel)
    HotelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Hotel.newBuilder() to construct.
  private Hotel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Hotel() {
    ime_ = "";
    grad_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Hotel();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return test1.HotelMotel.internal_static_Hotel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return test1.HotelMotel.internal_static_Hotel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            test1.Hotel.class, test1.Hotel.Builder.class);
  }

  public static final int IME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ime_ = "";
  /**
   * <code>string ime = 1;</code>
   * @return The ime.
   */
  @java.lang.Override
  public java.lang.String getIme() {
    java.lang.Object ref = ime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ime_ = s;
      return s;
    }
  }
  /**
   * <code>string ime = 1;</code>
   * @return The bytes for ime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImeBytes() {
    java.lang.Object ref = ime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZVEZDICE_FIELD_NUMBER = 2;
  private int zvezdice_ = 0;
  /**
   * <code>int32 zvezdice = 2;</code>
   * @return The zvezdice.
   */
  @java.lang.Override
  public int getZvezdice() {
    return zvezdice_;
  }

  public static final int UDALJENOSTI_OD_CENTRA_FIELD_NUMBER = 3;
  private int udaljenostiOdCentra_ = 0;
  /**
   * <code>int32 udaljenosti_od_centra = 3;</code>
   * @return The udaljenostiOdCentra.
   */
  @java.lang.Override
  public int getUdaljenostiOdCentra() {
    return udaljenostiOdCentra_;
  }

  public static final int BROJ_SLOBODNIH_MESTA_FIELD_NUMBER = 4;
  private int brojSlobodnihMesta_ = 0;
  /**
   * <code>int32 broj_slobodnih_mesta = 4;</code>
   * @return The brojSlobodnihMesta.
   */
  @java.lang.Override
  public int getBrojSlobodnihMesta() {
    return brojSlobodnihMesta_;
  }

  public static final int TRENUTNA_CENA_FIELD_NUMBER = 5;
  private int trenutnaCena_ = 0;
  /**
   * <code>int32 trenutna_cena = 5;</code>
   * @return The trenutnaCena.
   */
  @java.lang.Override
  public int getTrenutnaCena() {
    return trenutnaCena_;
  }

  public static final int GRAD_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object grad_ = "";
  /**
   * <code>string grad = 6;</code>
   * @return The grad.
   */
  @java.lang.Override
  public java.lang.String getGrad() {
    java.lang.Object ref = grad_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      grad_ = s;
      return s;
    }
  }
  /**
   * <code>string grad = 6;</code>
   * @return The bytes for grad.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGradBytes() {
    java.lang.Object ref = grad_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      grad_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 7;
  private int id_ = 0;
  /**
   * <code>int32 id = 7;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int BROJ_DANA_BORAVKA_FIELD_NUMBER = 10;
  private int brojDanaBoravka_ = 0;
  /**
   * <code>int32 broj_dana_boravka = 10;</code>
   * @return The brojDanaBoravka.
   */
  @java.lang.Override
  public int getBrojDanaBoravka() {
    return brojDanaBoravka_;
  }

  public static final int POCETAKBORAVKA_FIELD_NUMBER = 11;
  private long pocetakBoravka_ = 0L;
  /**
   * <code>int64 pocetakBoravka = 11;</code>
   * @return The pocetakBoravka.
   */
  @java.lang.Override
  public long getPocetakBoravka() {
    return pocetakBoravka_;
  }

  public static final int INTERNIRACUN_FIELD_NUMBER = 12;
  private int interniRacun_ = 0;
  /**
   * <code>int32 interniRacun = 12;</code>
   * @return The interniRacun.
   */
  @java.lang.Override
  public int getInterniRacun() {
    return interniRacun_;
  }

  public static final int PROVIZNIRACUN_FIELD_NUMBER = 13;
  private int provizniRacun_ = 0;
  /**
   * <code>int32 provizniRacun = 13;</code>
   * @return The provizniRacun.
   */
  @java.lang.Override
  public int getProvizniRacun() {
    return provizniRacun_;
  }

  public static final int DATUMPLACANJA_FIELD_NUMBER = 14;
  private long datumPlacanja_ = 0L;
  /**
   * <code>int64 datumPlacanja = 14;</code>
   * @return The datumPlacanja.
   */
  @java.lang.Override
  public long getDatumPlacanja() {
    return datumPlacanja_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ime_);
    }
    if (zvezdice_ != 0) {
      output.writeInt32(2, zvezdice_);
    }
    if (udaljenostiOdCentra_ != 0) {
      output.writeInt32(3, udaljenostiOdCentra_);
    }
    if (brojSlobodnihMesta_ != 0) {
      output.writeInt32(4, brojSlobodnihMesta_);
    }
    if (trenutnaCena_ != 0) {
      output.writeInt32(5, trenutnaCena_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grad_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, grad_);
    }
    if (id_ != 0) {
      output.writeInt32(7, id_);
    }
    if (brojDanaBoravka_ != 0) {
      output.writeInt32(10, brojDanaBoravka_);
    }
    if (pocetakBoravka_ != 0L) {
      output.writeInt64(11, pocetakBoravka_);
    }
    if (interniRacun_ != 0) {
      output.writeInt32(12, interniRacun_);
    }
    if (provizniRacun_ != 0) {
      output.writeInt32(13, provizniRacun_);
    }
    if (datumPlacanja_ != 0L) {
      output.writeInt64(14, datumPlacanja_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ime_);
    }
    if (zvezdice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, zvezdice_);
    }
    if (udaljenostiOdCentra_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, udaljenostiOdCentra_);
    }
    if (brojSlobodnihMesta_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, brojSlobodnihMesta_);
    }
    if (trenutnaCena_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, trenutnaCena_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grad_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, grad_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, id_);
    }
    if (brojDanaBoravka_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, brojDanaBoravka_);
    }
    if (pocetakBoravka_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, pocetakBoravka_);
    }
    if (interniRacun_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, interniRacun_);
    }
    if (provizniRacun_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, provizniRacun_);
    }
    if (datumPlacanja_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, datumPlacanja_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof test1.Hotel)) {
      return super.equals(obj);
    }
    test1.Hotel other = (test1.Hotel) obj;

    if (!getIme()
        .equals(other.getIme())) return false;
    if (getZvezdice()
        != other.getZvezdice()) return false;
    if (getUdaljenostiOdCentra()
        != other.getUdaljenostiOdCentra()) return false;
    if (getBrojSlobodnihMesta()
        != other.getBrojSlobodnihMesta()) return false;
    if (getTrenutnaCena()
        != other.getTrenutnaCena()) return false;
    if (!getGrad()
        .equals(other.getGrad())) return false;
    if (getId()
        != other.getId()) return false;
    if (getBrojDanaBoravka()
        != other.getBrojDanaBoravka()) return false;
    if (getPocetakBoravka()
        != other.getPocetakBoravka()) return false;
    if (getInterniRacun()
        != other.getInterniRacun()) return false;
    if (getProvizniRacun()
        != other.getProvizniRacun()) return false;
    if (getDatumPlacanja()
        != other.getDatumPlacanja()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IME_FIELD_NUMBER;
    hash = (53 * hash) + getIme().hashCode();
    hash = (37 * hash) + ZVEZDICE_FIELD_NUMBER;
    hash = (53 * hash) + getZvezdice();
    hash = (37 * hash) + UDALJENOSTI_OD_CENTRA_FIELD_NUMBER;
    hash = (53 * hash) + getUdaljenostiOdCentra();
    hash = (37 * hash) + BROJ_SLOBODNIH_MESTA_FIELD_NUMBER;
    hash = (53 * hash) + getBrojSlobodnihMesta();
    hash = (37 * hash) + TRENUTNA_CENA_FIELD_NUMBER;
    hash = (53 * hash) + getTrenutnaCena();
    hash = (37 * hash) + GRAD_FIELD_NUMBER;
    hash = (53 * hash) + getGrad().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + BROJ_DANA_BORAVKA_FIELD_NUMBER;
    hash = (53 * hash) + getBrojDanaBoravka();
    hash = (37 * hash) + POCETAKBORAVKA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPocetakBoravka());
    hash = (37 * hash) + INTERNIRACUN_FIELD_NUMBER;
    hash = (53 * hash) + getInterniRacun();
    hash = (37 * hash) + PROVIZNIRACUN_FIELD_NUMBER;
    hash = (53 * hash) + getProvizniRacun();
    hash = (37 * hash) + DATUMPLACANJA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDatumPlacanja());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test1.Hotel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.Hotel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.Hotel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.Hotel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.Hotel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.Hotel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.Hotel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.Hotel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.Hotel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static test1.Hotel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.Hotel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.Hotel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test1.Hotel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Hotel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Hotel)
      test1.HotelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test1.HotelMotel.internal_static_Hotel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test1.HotelMotel.internal_static_Hotel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test1.Hotel.class, test1.Hotel.Builder.class);
    }

    // Construct using test1.Hotel.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ime_ = "";
      zvezdice_ = 0;
      udaljenostiOdCentra_ = 0;
      brojSlobodnihMesta_ = 0;
      trenutnaCena_ = 0;
      grad_ = "";
      id_ = 0;
      brojDanaBoravka_ = 0;
      pocetakBoravka_ = 0L;
      interniRacun_ = 0;
      provizniRacun_ = 0;
      datumPlacanja_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return test1.HotelMotel.internal_static_Hotel_descriptor;
    }

    @java.lang.Override
    public test1.Hotel getDefaultInstanceForType() {
      return test1.Hotel.getDefaultInstance();
    }

    @java.lang.Override
    public test1.Hotel build() {
      test1.Hotel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public test1.Hotel buildPartial() {
      test1.Hotel result = new test1.Hotel(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(test1.Hotel result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ime_ = ime_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.zvezdice_ = zvezdice_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.udaljenostiOdCentra_ = udaljenostiOdCentra_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.brojSlobodnihMesta_ = brojSlobodnihMesta_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.trenutnaCena_ = trenutnaCena_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.grad_ = grad_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.brojDanaBoravka_ = brojDanaBoravka_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.pocetakBoravka_ = pocetakBoravka_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.interniRacun_ = interniRacun_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.provizniRacun_ = provizniRacun_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.datumPlacanja_ = datumPlacanja_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test1.Hotel) {
        return mergeFrom((test1.Hotel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test1.Hotel other) {
      if (other == test1.Hotel.getDefaultInstance()) return this;
      if (!other.getIme().isEmpty()) {
        ime_ = other.ime_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getZvezdice() != 0) {
        setZvezdice(other.getZvezdice());
      }
      if (other.getUdaljenostiOdCentra() != 0) {
        setUdaljenostiOdCentra(other.getUdaljenostiOdCentra());
      }
      if (other.getBrojSlobodnihMesta() != 0) {
        setBrojSlobodnihMesta(other.getBrojSlobodnihMesta());
      }
      if (other.getTrenutnaCena() != 0) {
        setTrenutnaCena(other.getTrenutnaCena());
      }
      if (!other.getGrad().isEmpty()) {
        grad_ = other.grad_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getBrojDanaBoravka() != 0) {
        setBrojDanaBoravka(other.getBrojDanaBoravka());
      }
      if (other.getPocetakBoravka() != 0L) {
        setPocetakBoravka(other.getPocetakBoravka());
      }
      if (other.getInterniRacun() != 0) {
        setInterniRacun(other.getInterniRacun());
      }
      if (other.getProvizniRacun() != 0) {
        setProvizniRacun(other.getProvizniRacun());
      }
      if (other.getDatumPlacanja() != 0L) {
        setDatumPlacanja(other.getDatumPlacanja());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              zvezdice_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              udaljenostiOdCentra_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              brojSlobodnihMesta_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              trenutnaCena_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              grad_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 80: {
              brojDanaBoravka_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 80
            case 88: {
              pocetakBoravka_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 88
            case 96: {
              interniRacun_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 96
            case 104: {
              provizniRacun_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 104
            case 112: {
              datumPlacanja_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 112
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ime_ = "";
    /**
     * <code>string ime = 1;</code>
     * @return The ime.
     */
    public java.lang.String getIme() {
      java.lang.Object ref = ime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ime = 1;</code>
     * @return The bytes for ime.
     */
    public com.google.protobuf.ByteString
        getImeBytes() {
      java.lang.Object ref = ime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ime = 1;</code>
     * @param value The ime to set.
     * @return This builder for chaining.
     */
    public Builder setIme(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ime_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIme() {
      ime_ = getDefaultInstance().getIme();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ime = 1;</code>
     * @param value The bytes for ime to set.
     * @return This builder for chaining.
     */
    public Builder setImeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ime_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int zvezdice_ ;
    /**
     * <code>int32 zvezdice = 2;</code>
     * @return The zvezdice.
     */
    @java.lang.Override
    public int getZvezdice() {
      return zvezdice_;
    }
    /**
     * <code>int32 zvezdice = 2;</code>
     * @param value The zvezdice to set.
     * @return This builder for chaining.
     */
    public Builder setZvezdice(int value) {

      zvezdice_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 zvezdice = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearZvezdice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      zvezdice_ = 0;
      onChanged();
      return this;
    }

    private int udaljenostiOdCentra_ ;
    /**
     * <code>int32 udaljenosti_od_centra = 3;</code>
     * @return The udaljenostiOdCentra.
     */
    @java.lang.Override
    public int getUdaljenostiOdCentra() {
      return udaljenostiOdCentra_;
    }
    /**
     * <code>int32 udaljenosti_od_centra = 3;</code>
     * @param value The udaljenostiOdCentra to set.
     * @return This builder for chaining.
     */
    public Builder setUdaljenostiOdCentra(int value) {

      udaljenostiOdCentra_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 udaljenosti_od_centra = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdaljenostiOdCentra() {
      bitField0_ = (bitField0_ & ~0x00000004);
      udaljenostiOdCentra_ = 0;
      onChanged();
      return this;
    }

    private int brojSlobodnihMesta_ ;
    /**
     * <code>int32 broj_slobodnih_mesta = 4;</code>
     * @return The brojSlobodnihMesta.
     */
    @java.lang.Override
    public int getBrojSlobodnihMesta() {
      return brojSlobodnihMesta_;
    }
    /**
     * <code>int32 broj_slobodnih_mesta = 4;</code>
     * @param value The brojSlobodnihMesta to set.
     * @return This builder for chaining.
     */
    public Builder setBrojSlobodnihMesta(int value) {

      brojSlobodnihMesta_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 broj_slobodnih_mesta = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrojSlobodnihMesta() {
      bitField0_ = (bitField0_ & ~0x00000008);
      brojSlobodnihMesta_ = 0;
      onChanged();
      return this;
    }

    private int trenutnaCena_ ;
    /**
     * <code>int32 trenutna_cena = 5;</code>
     * @return The trenutnaCena.
     */
    @java.lang.Override
    public int getTrenutnaCena() {
      return trenutnaCena_;
    }
    /**
     * <code>int32 trenutna_cena = 5;</code>
     * @param value The trenutnaCena to set.
     * @return This builder for chaining.
     */
    public Builder setTrenutnaCena(int value) {

      trenutnaCena_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trenutna_cena = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrenutnaCena() {
      bitField0_ = (bitField0_ & ~0x00000010);
      trenutnaCena_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object grad_ = "";
    /**
     * <code>string grad = 6;</code>
     * @return The grad.
     */
    public java.lang.String getGrad() {
      java.lang.Object ref = grad_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grad_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string grad = 6;</code>
     * @return The bytes for grad.
     */
    public com.google.protobuf.ByteString
        getGradBytes() {
      java.lang.Object ref = grad_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grad_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string grad = 6;</code>
     * @param value The grad to set.
     * @return This builder for chaining.
     */
    public Builder setGrad(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      grad_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string grad = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrad() {
      grad_ = getDefaultInstance().getGrad();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string grad = 6;</code>
     * @param value The bytes for grad to set.
     * @return This builder for chaining.
     */
    public Builder setGradBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      grad_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 7;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 7;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      id_ = 0;
      onChanged();
      return this;
    }

    private int brojDanaBoravka_ ;
    /**
     * <code>int32 broj_dana_boravka = 10;</code>
     * @return The brojDanaBoravka.
     */
    @java.lang.Override
    public int getBrojDanaBoravka() {
      return brojDanaBoravka_;
    }
    /**
     * <code>int32 broj_dana_boravka = 10;</code>
     * @param value The brojDanaBoravka to set.
     * @return This builder for chaining.
     */
    public Builder setBrojDanaBoravka(int value) {

      brojDanaBoravka_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 broj_dana_boravka = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrojDanaBoravka() {
      bitField0_ = (bitField0_ & ~0x00000080);
      brojDanaBoravka_ = 0;
      onChanged();
      return this;
    }

    private long pocetakBoravka_ ;
    /**
     * <code>int64 pocetakBoravka = 11;</code>
     * @return The pocetakBoravka.
     */
    @java.lang.Override
    public long getPocetakBoravka() {
      return pocetakBoravka_;
    }
    /**
     * <code>int64 pocetakBoravka = 11;</code>
     * @param value The pocetakBoravka to set.
     * @return This builder for chaining.
     */
    public Builder setPocetakBoravka(long value) {

      pocetakBoravka_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pocetakBoravka = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPocetakBoravka() {
      bitField0_ = (bitField0_ & ~0x00000100);
      pocetakBoravka_ = 0L;
      onChanged();
      return this;
    }

    private int interniRacun_ ;
    /**
     * <code>int32 interniRacun = 12;</code>
     * @return The interniRacun.
     */
    @java.lang.Override
    public int getInterniRacun() {
      return interniRacun_;
    }
    /**
     * <code>int32 interniRacun = 12;</code>
     * @param value The interniRacun to set.
     * @return This builder for chaining.
     */
    public Builder setInterniRacun(int value) {

      interniRacun_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 interniRacun = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterniRacun() {
      bitField0_ = (bitField0_ & ~0x00000200);
      interniRacun_ = 0;
      onChanged();
      return this;
    }

    private int provizniRacun_ ;
    /**
     * <code>int32 provizniRacun = 13;</code>
     * @return The provizniRacun.
     */
    @java.lang.Override
    public int getProvizniRacun() {
      return provizniRacun_;
    }
    /**
     * <code>int32 provizniRacun = 13;</code>
     * @param value The provizniRacun to set.
     * @return This builder for chaining.
     */
    public Builder setProvizniRacun(int value) {

      provizniRacun_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 provizniRacun = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvizniRacun() {
      bitField0_ = (bitField0_ & ~0x00000400);
      provizniRacun_ = 0;
      onChanged();
      return this;
    }

    private long datumPlacanja_ ;
    /**
     * <code>int64 datumPlacanja = 14;</code>
     * @return The datumPlacanja.
     */
    @java.lang.Override
    public long getDatumPlacanja() {
      return datumPlacanja_;
    }
    /**
     * <code>int64 datumPlacanja = 14;</code>
     * @param value The datumPlacanja to set.
     * @return This builder for chaining.
     */
    public Builder setDatumPlacanja(long value) {

      datumPlacanja_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 datumPlacanja = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatumPlacanja() {
      bitField0_ = (bitField0_ & ~0x00000800);
      datumPlacanja_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Hotel)
  }

  // @@protoc_insertion_point(class_scope:Hotel)
  private static final test1.Hotel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test1.Hotel();
  }

  public static test1.Hotel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Hotel>
      PARSER = new com.google.protobuf.AbstractParser<Hotel>() {
    @java.lang.Override
    public Hotel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Hotel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Hotel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public test1.Hotel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

