// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

public final class HotelMotel {
  private HotelMotel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hotel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hotel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RezervacijaInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RezervacijaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpitZaHotele_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpitZaHotele_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rezervacija_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rezervacija_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020hotelMotel.proto\"\213\002\n\005Hotel\022\013\n\003ime\030\001 \001(" +
      "\t\022\020\n\010zvezdice\030\002 \001(\005\022\035\n\025udaljenosti_od_ce" +
      "ntra\030\003 \001(\005\022\034\n\024broj_slobodnih_mesta\030\004 \001(\005" +
      "\022\025\n\rtrenutna_cena\030\005 \001(\005\022\014\n\004grad\030\006 \001(\t\022\n\n" +
      "\002id\030\007 \001(\005\022\031\n\021broj_dana_boravka\030\n \001(\005\022\026\n\016" +
      "pocetakBoravka\030\013 \001(\003\022\024\n\014interniRacun\030\014 \001" +
      "(\005\022\025\n\rprovizniRacun\030\r \001(\005\022\025\n\rdatumPlacan" +
      "ja\030\016 \001(\003\"R\n\017RezervacijaInfo\022\025\n\005hotel\030\001 \001" +
      "(\0132\006.Hotel\022\026\n\016pocetakBoravka\030\002 \001(\003\022\020\n\010br" +
      "ojDana\030\003 \001(\005\"H\n\014UpitZaHotele\022\014\n\004grad\030\001 \001" +
      "(\t\022\026\n\016max_udaljenost\030\002 \001(\005\022\022\n\nmin_zvezde" +
      "\030\003 \001(\005\"q\n\013Rezervacija\022\n\n\002id\030\001 \001(\005\022\025\n\005hot" +
      "el\030\002 \001(\0132\006.Hotel\022\026\n\016pocetakBoravka\030\003 \001(\003" +
      "\022\020\n\010brojDana\030\004 \001(\005\022\025\n\rrokZaPlacanje\030\005 \001(" +
      "\0032\231\001\n\014HotelService\022!\n\004Upit\022\r.UpitZaHotel" +
      "e\032\006.Hotel\"\0000\001\022-\n\tRezervisi\022\020.Rezervacija" +
      "Info\032\014.Rezervacija\"\000\0227\n\021otkaziRezervacij" +
      "u\022\020.RezervacijaInfo\032\014.Rezervacija\"\0000\001B\t\n" +
      "\005test1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Hotel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hotel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hotel_descriptor,
        new java.lang.String[] { "Ime", "Zvezdice", "UdaljenostiOdCentra", "BrojSlobodnihMesta", "TrenutnaCena", "Grad", "Id", "BrojDanaBoravka", "PocetakBoravka", "InterniRacun", "ProvizniRacun", "DatumPlacanja", });
    internal_static_RezervacijaInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RezervacijaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RezervacijaInfo_descriptor,
        new java.lang.String[] { "Hotel", "PocetakBoravka", "BrojDana", });
    internal_static_UpitZaHotele_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpitZaHotele_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpitZaHotele_descriptor,
        new java.lang.String[] { "Grad", "MaxUdaljenost", "MinZvezde", });
    internal_static_Rezervacija_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Rezervacija_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rezervacija_descriptor,
        new java.lang.String[] { "Id", "Hotel", "PocetakBoravka", "BrojDana", "RokZaPlacanje", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
