// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

/**
 * Protobuf type {@code RezervacijaInfo}
 */
public final class RezervacijaInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RezervacijaInfo)
    RezervacijaInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RezervacijaInfo.newBuilder() to construct.
  private RezervacijaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RezervacijaInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RezervacijaInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return test1.HotelMotel.internal_static_RezervacijaInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return test1.HotelMotel.internal_static_RezervacijaInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            test1.RezervacijaInfo.class, test1.RezervacijaInfo.Builder.class);
  }

  public static final int HOTEL_FIELD_NUMBER = 1;
  private test1.Hotel hotel_;
  /**
   * <code>.Hotel hotel = 1;</code>
   * @return Whether the hotel field is set.
   */
  @java.lang.Override
  public boolean hasHotel() {
    return hotel_ != null;
  }
  /**
   * <code>.Hotel hotel = 1;</code>
   * @return The hotel.
   */
  @java.lang.Override
  public test1.Hotel getHotel() {
    return hotel_ == null ? test1.Hotel.getDefaultInstance() : hotel_;
  }
  /**
   * <code>.Hotel hotel = 1;</code>
   */
  @java.lang.Override
  public test1.HotelOrBuilder getHotelOrBuilder() {
    return hotel_ == null ? test1.Hotel.getDefaultInstance() : hotel_;
  }

  public static final int POCETAKBORAVKA_FIELD_NUMBER = 2;
  private long pocetakBoravka_ = 0L;
  /**
   * <code>int64 pocetakBoravka = 2;</code>
   * @return The pocetakBoravka.
   */
  @java.lang.Override
  public long getPocetakBoravka() {
    return pocetakBoravka_;
  }

  public static final int BROJDANA_FIELD_NUMBER = 3;
  private int brojDana_ = 0;
  /**
   * <code>int32 brojDana = 3;</code>
   * @return The brojDana.
   */
  @java.lang.Override
  public int getBrojDana() {
    return brojDana_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hotel_ != null) {
      output.writeMessage(1, getHotel());
    }
    if (pocetakBoravka_ != 0L) {
      output.writeInt64(2, pocetakBoravka_);
    }
    if (brojDana_ != 0) {
      output.writeInt32(3, brojDana_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hotel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHotel());
    }
    if (pocetakBoravka_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, pocetakBoravka_);
    }
    if (brojDana_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, brojDana_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof test1.RezervacijaInfo)) {
      return super.equals(obj);
    }
    test1.RezervacijaInfo other = (test1.RezervacijaInfo) obj;

    if (hasHotel() != other.hasHotel()) return false;
    if (hasHotel()) {
      if (!getHotel()
          .equals(other.getHotel())) return false;
    }
    if (getPocetakBoravka()
        != other.getPocetakBoravka()) return false;
    if (getBrojDana()
        != other.getBrojDana()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHotel()) {
      hash = (37 * hash) + HOTEL_FIELD_NUMBER;
      hash = (53 * hash) + getHotel().hashCode();
    }
    hash = (37 * hash) + POCETAKBORAVKA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPocetakBoravka());
    hash = (37 * hash) + BROJDANA_FIELD_NUMBER;
    hash = (53 * hash) + getBrojDana();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test1.RezervacijaInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.RezervacijaInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.RezervacijaInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.RezervacijaInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.RezervacijaInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.RezervacijaInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.RezervacijaInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.RezervacijaInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.RezervacijaInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static test1.RezervacijaInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.RezervacijaInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.RezervacijaInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test1.RezervacijaInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RezervacijaInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RezervacijaInfo)
      test1.RezervacijaInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test1.HotelMotel.internal_static_RezervacijaInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test1.HotelMotel.internal_static_RezervacijaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test1.RezervacijaInfo.class, test1.RezervacijaInfo.Builder.class);
    }

    // Construct using test1.RezervacijaInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hotel_ = null;
      if (hotelBuilder_ != null) {
        hotelBuilder_.dispose();
        hotelBuilder_ = null;
      }
      pocetakBoravka_ = 0L;
      brojDana_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return test1.HotelMotel.internal_static_RezervacijaInfo_descriptor;
    }

    @java.lang.Override
    public test1.RezervacijaInfo getDefaultInstanceForType() {
      return test1.RezervacijaInfo.getDefaultInstance();
    }

    @java.lang.Override
    public test1.RezervacijaInfo build() {
      test1.RezervacijaInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public test1.RezervacijaInfo buildPartial() {
      test1.RezervacijaInfo result = new test1.RezervacijaInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(test1.RezervacijaInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hotel_ = hotelBuilder_ == null
            ? hotel_
            : hotelBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pocetakBoravka_ = pocetakBoravka_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.brojDana_ = brojDana_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test1.RezervacijaInfo) {
        return mergeFrom((test1.RezervacijaInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test1.RezervacijaInfo other) {
      if (other == test1.RezervacijaInfo.getDefaultInstance()) return this;
      if (other.hasHotel()) {
        mergeHotel(other.getHotel());
      }
      if (other.getPocetakBoravka() != 0L) {
        setPocetakBoravka(other.getPocetakBoravka());
      }
      if (other.getBrojDana() != 0) {
        setBrojDana(other.getBrojDana());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHotelFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              pocetakBoravka_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              brojDana_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private test1.Hotel hotel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        test1.Hotel, test1.Hotel.Builder, test1.HotelOrBuilder> hotelBuilder_;
    /**
     * <code>.Hotel hotel = 1;</code>
     * @return Whether the hotel field is set.
     */
    public boolean hasHotel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     * @return The hotel.
     */
    public test1.Hotel getHotel() {
      if (hotelBuilder_ == null) {
        return hotel_ == null ? test1.Hotel.getDefaultInstance() : hotel_;
      } else {
        return hotelBuilder_.getMessage();
      }
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public Builder setHotel(test1.Hotel value) {
      if (hotelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hotel_ = value;
      } else {
        hotelBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public Builder setHotel(
        test1.Hotel.Builder builderForValue) {
      if (hotelBuilder_ == null) {
        hotel_ = builderForValue.build();
      } else {
        hotelBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public Builder mergeHotel(test1.Hotel value) {
      if (hotelBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          hotel_ != null &&
          hotel_ != test1.Hotel.getDefaultInstance()) {
          getHotelBuilder().mergeFrom(value);
        } else {
          hotel_ = value;
        }
      } else {
        hotelBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public Builder clearHotel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hotel_ = null;
      if (hotelBuilder_ != null) {
        hotelBuilder_.dispose();
        hotelBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public test1.Hotel.Builder getHotelBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHotelFieldBuilder().getBuilder();
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    public test1.HotelOrBuilder getHotelOrBuilder() {
      if (hotelBuilder_ != null) {
        return hotelBuilder_.getMessageOrBuilder();
      } else {
        return hotel_ == null ?
            test1.Hotel.getDefaultInstance() : hotel_;
      }
    }
    /**
     * <code>.Hotel hotel = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        test1.Hotel, test1.Hotel.Builder, test1.HotelOrBuilder> 
        getHotelFieldBuilder() {
      if (hotelBuilder_ == null) {
        hotelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            test1.Hotel, test1.Hotel.Builder, test1.HotelOrBuilder>(
                getHotel(),
                getParentForChildren(),
                isClean());
        hotel_ = null;
      }
      return hotelBuilder_;
    }

    private long pocetakBoravka_ ;
    /**
     * <code>int64 pocetakBoravka = 2;</code>
     * @return The pocetakBoravka.
     */
    @java.lang.Override
    public long getPocetakBoravka() {
      return pocetakBoravka_;
    }
    /**
     * <code>int64 pocetakBoravka = 2;</code>
     * @param value The pocetakBoravka to set.
     * @return This builder for chaining.
     */
    public Builder setPocetakBoravka(long value) {

      pocetakBoravka_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pocetakBoravka = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPocetakBoravka() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pocetakBoravka_ = 0L;
      onChanged();
      return this;
    }

    private int brojDana_ ;
    /**
     * <code>int32 brojDana = 3;</code>
     * @return The brojDana.
     */
    @java.lang.Override
    public int getBrojDana() {
      return brojDana_;
    }
    /**
     * <code>int32 brojDana = 3;</code>
     * @param value The brojDana to set.
     * @return This builder for chaining.
     */
    public Builder setBrojDana(int value) {

      brojDana_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 brojDana = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrojDana() {
      bitField0_ = (bitField0_ & ~0x00000004);
      brojDana_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RezervacijaInfo)
  }

  // @@protoc_insertion_point(class_scope:RezervacijaInfo)
  private static final test1.RezervacijaInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test1.RezervacijaInfo();
  }

  public static test1.RezervacijaInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RezervacijaInfo>
      PARSER = new com.google.protobuf.AbstractParser<RezervacijaInfo>() {
    @java.lang.Override
    public RezervacijaInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RezervacijaInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RezervacijaInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public test1.RezervacijaInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

