// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

public interface RezervacijaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Rezervacija)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.Hotel hotel = 2;</code>
   * @return Whether the hotel field is set.
   */
  boolean hasHotel();
  /**
   * <code>.Hotel hotel = 2;</code>
   * @return The hotel.
   */
  test1.Hotel getHotel();
  /**
   * <code>.Hotel hotel = 2;</code>
   */
  test1.HotelOrBuilder getHotelOrBuilder();

  /**
   * <code>int64 pocetakBoravka = 3;</code>
   * @return The pocetakBoravka.
   */
  long getPocetakBoravka();

  /**
   * <code>int32 brojDana = 4;</code>
   * @return The brojDana.
   */
  int getBrojDana();

  /**
   * <code>int64 rokZaPlacanje = 5;</code>
   * @return The rokZaPlacanje.
   */
  long getRokZaPlacanje();
}
