// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

public interface RezervacijaInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RezervacijaInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Hotel hotel = 1;</code>
   * @return Whether the hotel field is set.
   */
  boolean hasHotel();
  /**
   * <code>.Hotel hotel = 1;</code>
   * @return The hotel.
   */
  test1.Hotel getHotel();
  /**
   * <code>.Hotel hotel = 1;</code>
   */
  test1.HotelOrBuilder getHotelOrBuilder();

  /**
   * <code>int64 pocetakBoravka = 2;</code>
   * @return The pocetakBoravka.
   */
  long getPocetakBoravka();

  /**
   * <code>int32 brojDana = 3;</code>
   * @return The brojDana.
   */
  int getBrojDana();
}
