// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

/**
 * Protobuf type {@code UpitZaHotele}
 */
public final class UpitZaHotele extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpitZaHotele)
    UpitZaHoteleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpitZaHotele.newBuilder() to construct.
  private UpitZaHotele(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpitZaHotele() {
    grad_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpitZaHotele();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return test1.HotelMotel.internal_static_UpitZaHotele_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return test1.HotelMotel.internal_static_UpitZaHotele_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            test1.UpitZaHotele.class, test1.UpitZaHotele.Builder.class);
  }

  public static final int GRAD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object grad_ = "";
  /**
   * <code>string grad = 1;</code>
   * @return The grad.
   */
  @java.lang.Override
  public java.lang.String getGrad() {
    java.lang.Object ref = grad_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      grad_ = s;
      return s;
    }
  }
  /**
   * <code>string grad = 1;</code>
   * @return The bytes for grad.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGradBytes() {
    java.lang.Object ref = grad_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      grad_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_UDALJENOST_FIELD_NUMBER = 2;
  private int maxUdaljenost_ = 0;
  /**
   * <code>int32 max_udaljenost = 2;</code>
   * @return The maxUdaljenost.
   */
  @java.lang.Override
  public int getMaxUdaljenost() {
    return maxUdaljenost_;
  }

  public static final int MIN_ZVEZDE_FIELD_NUMBER = 3;
  private int minZvezde_ = 0;
  /**
   * <code>int32 min_zvezde = 3;</code>
   * @return The minZvezde.
   */
  @java.lang.Override
  public int getMinZvezde() {
    return minZvezde_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grad_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, grad_);
    }
    if (maxUdaljenost_ != 0) {
      output.writeInt32(2, maxUdaljenost_);
    }
    if (minZvezde_ != 0) {
      output.writeInt32(3, minZvezde_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grad_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, grad_);
    }
    if (maxUdaljenost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, maxUdaljenost_);
    }
    if (minZvezde_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, minZvezde_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof test1.UpitZaHotele)) {
      return super.equals(obj);
    }
    test1.UpitZaHotele other = (test1.UpitZaHotele) obj;

    if (!getGrad()
        .equals(other.getGrad())) return false;
    if (getMaxUdaljenost()
        != other.getMaxUdaljenost()) return false;
    if (getMinZvezde()
        != other.getMinZvezde()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRAD_FIELD_NUMBER;
    hash = (53 * hash) + getGrad().hashCode();
    hash = (37 * hash) + MAX_UDALJENOST_FIELD_NUMBER;
    hash = (53 * hash) + getMaxUdaljenost();
    hash = (37 * hash) + MIN_ZVEZDE_FIELD_NUMBER;
    hash = (53 * hash) + getMinZvezde();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test1.UpitZaHotele parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.UpitZaHotele parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.UpitZaHotele parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.UpitZaHotele parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.UpitZaHotele parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test1.UpitZaHotele parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test1.UpitZaHotele parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.UpitZaHotele parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.UpitZaHotele parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static test1.UpitZaHotele parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test1.UpitZaHotele parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test1.UpitZaHotele parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test1.UpitZaHotele prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpitZaHotele}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpitZaHotele)
      test1.UpitZaHoteleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test1.HotelMotel.internal_static_UpitZaHotele_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test1.HotelMotel.internal_static_UpitZaHotele_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test1.UpitZaHotele.class, test1.UpitZaHotele.Builder.class);
    }

    // Construct using test1.UpitZaHotele.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      grad_ = "";
      maxUdaljenost_ = 0;
      minZvezde_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return test1.HotelMotel.internal_static_UpitZaHotele_descriptor;
    }

    @java.lang.Override
    public test1.UpitZaHotele getDefaultInstanceForType() {
      return test1.UpitZaHotele.getDefaultInstance();
    }

    @java.lang.Override
    public test1.UpitZaHotele build() {
      test1.UpitZaHotele result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public test1.UpitZaHotele buildPartial() {
      test1.UpitZaHotele result = new test1.UpitZaHotele(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(test1.UpitZaHotele result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.grad_ = grad_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxUdaljenost_ = maxUdaljenost_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minZvezde_ = minZvezde_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test1.UpitZaHotele) {
        return mergeFrom((test1.UpitZaHotele)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test1.UpitZaHotele other) {
      if (other == test1.UpitZaHotele.getDefaultInstance()) return this;
      if (!other.getGrad().isEmpty()) {
        grad_ = other.grad_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getMaxUdaljenost() != 0) {
        setMaxUdaljenost(other.getMaxUdaljenost());
      }
      if (other.getMinZvezde() != 0) {
        setMinZvezde(other.getMinZvezde());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grad_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              maxUdaljenost_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              minZvezde_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object grad_ = "";
    /**
     * <code>string grad = 1;</code>
     * @return The grad.
     */
    public java.lang.String getGrad() {
      java.lang.Object ref = grad_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grad_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string grad = 1;</code>
     * @return The bytes for grad.
     */
    public com.google.protobuf.ByteString
        getGradBytes() {
      java.lang.Object ref = grad_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grad_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string grad = 1;</code>
     * @param value The grad to set.
     * @return This builder for chaining.
     */
    public Builder setGrad(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      grad_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string grad = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrad() {
      grad_ = getDefaultInstance().getGrad();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string grad = 1;</code>
     * @param value The bytes for grad to set.
     * @return This builder for chaining.
     */
    public Builder setGradBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      grad_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int maxUdaljenost_ ;
    /**
     * <code>int32 max_udaljenost = 2;</code>
     * @return The maxUdaljenost.
     */
    @java.lang.Override
    public int getMaxUdaljenost() {
      return maxUdaljenost_;
    }
    /**
     * <code>int32 max_udaljenost = 2;</code>
     * @param value The maxUdaljenost to set.
     * @return This builder for chaining.
     */
    public Builder setMaxUdaljenost(int value) {

      maxUdaljenost_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_udaljenost = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxUdaljenost() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxUdaljenost_ = 0;
      onChanged();
      return this;
    }

    private int minZvezde_ ;
    /**
     * <code>int32 min_zvezde = 3;</code>
     * @return The minZvezde.
     */
    @java.lang.Override
    public int getMinZvezde() {
      return minZvezde_;
    }
    /**
     * <code>int32 min_zvezde = 3;</code>
     * @param value The minZvezde to set.
     * @return This builder for chaining.
     */
    public Builder setMinZvezde(int value) {

      minZvezde_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 min_zvezde = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinZvezde() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minZvezde_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpitZaHotele)
  }

  // @@protoc_insertion_point(class_scope:UpitZaHotele)
  private static final test1.UpitZaHotele DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test1.UpitZaHotele();
  }

  public static test1.UpitZaHotele getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpitZaHotele>
      PARSER = new com.google.protobuf.AbstractParser<UpitZaHotele>() {
    @java.lang.Override
    public UpitZaHotele parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpitZaHotele> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpitZaHotele> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public test1.UpitZaHotele getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

