// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelMotel.proto

package test1;

public interface UpitZaHoteleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpitZaHotele)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string grad = 1;</code>
   * @return The grad.
   */
  java.lang.String getGrad();
  /**
   * <code>string grad = 1;</code>
   * @return The bytes for grad.
   */
  com.google.protobuf.ByteString
      getGradBytes();

  /**
   * <code>int32 max_udaljenost = 2;</code>
   * @return The maxUdaljenost.
   */
  int getMaxUdaljenost();

  /**
   * <code>int32 min_zvezde = 3;</code>
   * @return The minZvezde.
   */
  int getMinZvezde();
}
